version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: unless-stopped
        networks:
         - inception
        volumes:
         - db_vol:/var/lib/mysql/
        env_file: .env

    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        depends_on:
         - wordpress
        ports:
         - "443:443"
        restart: unless-stopped
        networks:
         - inception
        volumes:
         - wp_vol:/var/www/wordpress
        env_file: .env

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        depends_on:
         - mariadb
        restart: unless-stopped
        networks:
         - inception
        volumes:
         - wp_vol:/var/www/wordpress
        env_file: .env

    traefik:
        container_name: traefik
        build: ./requirements/bonus/traefik
        volumes:
          # So that Traefik can listen to the Docker events
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - inception
        ports:
          - "80:80"
          - "8080:8080"
    # static_web:
    #     container_name: static_web
    #     build: ./requirements/bonus/static
    #     volumes:
    #       - static_vol:/var/www/static
    #     networks:
    #       - inception
    #     ports:

volumes:
     wp_vol:
         driver: local
         driver_opts:
             type: 'none'
             o: 'bind'
             device: '/home/ktashbae/data/wordpress'
     db_vol:
         driver: local
         driver_opts:
             type: 'none'
             o: 'bind'
             device: '/home/ktashbae/data/db'
    #  static_vol:
    #     driver: local
    #     driver_opts:
    #         type: 'none'
    #         o: 'bind'
    #         device: '/home/ktashbae/data/static'

networks:
    inception:
