version: "3"
services: 
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - "mariadb:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
# enables the wordpress service to communicate 
# with the mysql service
    links:
      - mariadb
    volumes:
      - "wordpress:/var/www/wordpress"
# services are started and stopped in the dependency order
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
  
  nginx:
    image: nginx:alpine
    container_name: nginx
# maps the host machine port 8080 to the container port 80.
    depends_on:
      - wordpress
    ports:
      - 8080:80
    volumes:
      #- ./requirements/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d
      - "wordpress:/var/www/wordpress"
#  enables the wordpress service to communicate with the mysql service.
    links:
      - wordpress

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: '/home/ktashbae/data/db'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: '/home/ktashbae/data/wordpress'