version: '3.8'

services:
    mariadb:
        container_name: mariadb
        image: mariadb
        build: ./requirements/mariadb
        restart: unless-stopped
        networks:
         - inception
        volumes:
         - db_vol:/var/lib/mysql/
        env_file: .env

    nginx:
        container_name: nginx
        image: nginx
        build: ./requirements/nginx/
        depends_on:
         - wordpress
        ports:
         - "443:443"
        restart: unless-stopped
        networks:
         - inception
        volumes:
         - wp_vol:/var/www/wordpress
        env_file: .env

    wordpress:
        container_name: wordpress
        image: wordpress
        build: ./requirements/wordpress/
        depends_on:
         - mariadb
        restart: unless-stopped
        networks:
         - inception
        volumes:
         - wp_vol:/var/www/wordpress
        env_file: .env

################### BONUS ##########################
    traefik:
        container_name: traefik
        image: traefik
        build: ./requirements/bonus/traefik
        restart: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - inception
        ports:
          - "80:80"
          - "8080:8080"

    ftp:
        container_name: ftp
        image: ftp
        build: ./requirements/bonus/ftp
        depends_on:
          - nginx
        restart: unless-stopped
        volumes:
          - wp_vol:/var/www/wordpress
        networks:
          - inception
        ports:
          - "21:21"
          - "21100-21110:21100-21110"
        env_file: .env

volumes:
     wp_vol:
         driver: local
         driver_opts:
             type: 'none'
             o: 'bind'
             device: '/home/ktashbae/data/wordpress'
     db_vol:
         driver: local
         driver_opts:
             type: 'none'
             o: 'bind'
             device: '/home/ktashbae/data/db'

networks:
    inception:
