version: '3.8'

services:
    #MARIDB
    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        container_name: "mariadb"
        ports: 
          - 3306:3306
        volumes:
            - db:/var/lib/mysql
        env_file: .env
        restart: unless-stopped
        networks:
          - inception

    #WORDPRESS
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        ports:
            - 9000:9000
        depends_on:
            - mariadb
        volumes:
            - wp_db:/var/www/html
        env_file: .env
        environment:
            - WORDPRESS_DB_HOST=mysql:3306
            - WORDPRESS_DB_USER=$MYSQL_USER
            - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
            - WORDPRESS_DB_NAME=$MYSQL_DATABASE
        restart: unless-stopped
        networks:
          - inception

    #NGINX
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: "nginx"
        ports:
            - 443:443
        depends_on:
            - wordpress
        volumes:
            - wp_db:/var/www/html
        restart: unless-stopped
        networks:
            - inception

networks:
    inception:
        driver: bridge

volumes:
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/ktashbae/data/db
    wp_db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/ktashbae/data/wordpress
