version: '3.8'

services:
    #MARIDB
    mariadb:
        build:
            context: ./requirements/mariadb
        volumes:
            - db:/var/lib/mysql
        restart: always
    #NGINX
    nginx:
        build:
            context: ./requirements/nginx
        ports:
            - 4343:443
        restart: always
    #WORDPRESS
    wordpress:
        build:
            context: ./requirements/wordpress
        ports:
            - 9000:9000
        depends_on:
            - mariadb
        restart: always

networks:
    inception:
        driver: bridge

volumes:
    db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/ktashbae/data/db
    wp_db:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/ktashbae/data/wordpress
