version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: unless-stopped
        networks:
         - inception
        volumes:
         - db_vol:/var/lib/mysql/
        env_file: .env

    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        depends_on:
         - wordpress
        ports:
         - "443:443"
        restart: unless-stopped
        networks:
         - inception
        volumes:
         - wp_vol:/var/www/

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        depends_on:
         - mariadb
        restart: unless-stopped
        networks:
         - inception
        volumes:
         - wp_vol:/var/www/
        env_file: .env

networks:
     inception:

volumes:
     wp_vol:
         driver: local
         driver_opts:
             type: 'none'
             o: 'bind'
             device: '/home/ktashbae/data/wordpress'
     db_vol:
         driver: local
         driver_opts:
             type: 'none'
             o: 'bind'
             device: '/home/ktashbae/data/db'
