version: '3'
services:
  php:
    image: php:7.4-fpm
    volumes:
      - './src:/var/www/html'
  nginx:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root42
