CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'user42' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON wordpress.*
  TO 'user42'@'localhost' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS phpmyadmin;
CREATE USER IF NOT EXISTS 'ktashbae42' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.*
  TO 'ktashbae42'@'localhost' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
