CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE
  DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
CREATE USER IF NOT EXISTS '$MYSQL_USER' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.*
  TO '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
FLUSH PRIVILEGES;